var sons = ['jojo.mp3',
    'Jojoentrance.mp3',
    'jojoOrganisé.mp3',
    'discord.mp3',
    'prout.mp3',
    'PasMal.mp3',
    'dalila1.mp3',
    'among-us.mp3',
    'grosPD.mp3',
    'Pivert.mp3',
    'Pipi_Math.mp3',
    'DroguePivert.mp3',
    'Ekip.mp3',
    'ErreurGrave.mp3',
    'bombes.mp3',
    'Moliere.mp3',
    'Lavabo.mp3',
    'RienAfaireIci.mp3',
    'brunoChinois.mp3',
    '0autorite.mp3',
    'BrunoDebat.mp3',
    'Jaouad-le-cochon.mp3',   
    'JPP.mp3',
    'Bosh.mp3',
    'viveHitler.mp3',
    'CKiHitler.mp3',
    'E.mp3',   
    'PrblmdeCo.mp3',
    'intrestingAnneSO.mp3',
    'quiprendliddelulu.mp3',
    'VacancesAnneSO.mp3',
    'SamLacoupe.mp3',
    'Petitdej.mp3',
    'anal.mp3',
    'meaDami.mp3',    
    'JCVD.mp3',
    'dominou.mp3',
    'DamienViolent.mp3',
    'Sophie-cochonne.mp3',
    'remarque.mp3',
    'bite.mp3',
    'cancer.mp3',
    'rigolade.mp3',
    'humm.mp3',
    'chieur.mp3',
    'enfoirés.mp3',
    'revolution.mp3',
    'windows.mp3',
    'voyou.mp3'
            ]











var pics = ['Joel_Colloc.jpg',
    'jojoEntrance.png',
    'jojoOrganise.PNG',
    'discord.png',
    'lulu.jpg',
    'anneSo.png',
    'dalilouche.jpg',
    'among-us-logo.jpg',
    'damien.jpeg',
    'pivert.jpeg',
    'math_lepivert.jpg',
    'Substance.png',
    'Ekip.jpeg',
    'SSPivert.png',
    'TerroristePivert.JPG',
    'Moliere.JPG',
    'IssouLavabo.JPG',
    'ConfusedPivert.jpg',
    'bruno.png',
    'brunoVnr.JPEG',
    'pereBruno.JPEG',
    'jaouad2bit.JPEG',
    'jpp.png',
    'Bosh.jpeg',
    'viveAnneSo.jpg',
    'QuiEstHitler.jpg',
    'E.jpeg',   
    'NoCoAnneSo.JPG',
    'intrestingAnneSO.JPEG',
    'imposteurLulu.JPG',
    'AnneSoClaus.JPG',
    'OHMYANNE_SO.JPG',
    'PetitDej.JPG',
    'anal.JPG',
    'damilouche.JPG',
    'JCVD.png',
    'Dominique.jpg',
    'DamienViolent.jpeg',
    'sophie.JPG',
    'serin_zoom.JPG',
    'penis_serin.JPG',
    'inutile.JPG',
    'serin.jpg',
    'yamete.JPEG',
    'serin_fume.JPG',
    'issou_serin.JPG',
    'bagarre.JPG',
    'windows.JPG',
    'voyou.JPG'
    ]
